# Generated by Django 6.0.1 on 2026-01-31 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_id', models.IntegerField()),
                ('s_name', models.CharField(max_length=64)),
                ('s_dept', models.CharField(max_length=64)),
            ],
        ),
    ]
