# Generated by Django 6.0.2 on 2026-02-23 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='students',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Students'},
        ),
        migrations.AddField(
            model_name='students',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='students',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='students',
            name='s_dept',
            field=models.CharField(help_text='Department of the student', max_length=64),
        ),
        migrations.AlterField(
            model_name='students',
            name='s_id',
            field=models.IntegerField(help_text='Unique student identifier', unique=True),
        ),
        migrations.AlterField(
            model_name='students',
            name='s_name',
            field=models.CharField(help_text='Full name of the student', max_length=64),
        ),
    ]
